channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.1.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - pydot==4.0.1
  - torch==2.7.1
  - tqdm==4.67.1
name: mlflow-env
