version: '3.8'

services:
  mlflow-server:
    image: python:3.8
    command: >
      sh -c "pip install mlflow &&
      mlflow server --backend-store-uri sqlite:////app/mlflow.db
      --default-artifact-root /app/mlruns
      --host 0.0.0.0
      --port 5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    ports:
      - "5000:5000"
    networks:
      - xray-network

  xray-train:
    build: .
    depends_on:
      - mlflow-server
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    networks:
      - xray-network

networks:
  xray-network:
    driver: bridge
